
/* Drop Tables */

DROP TABLE SOLDESK.BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE SOLDESK.MEMBER CASCADE CONSTRAINTS;
DROP TABLE SOLDESK.MEMBER_BOARD CASCADE CONSTRAINTS;
DROP TABLE SOLDESK.MOVIERANK CASCADE CONSTRAINTS;
DROP TABLE SOLDESK.MOVIEREVIEW CASCADE CONSTRAINTS;
DROP TABLE SOLDESK.MOVIESCRAP CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SOLDESK.BOARD_NUM;
DROP SEQUENCE SOLDESK.COMMENT_SEQ;
DROP SEQUENCE SOLDESK.SEQ_MEMBER_NUM;




/* Create Sequences */

CREATE SEQUENCE SOLDESK.BOARD_NUM INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 83 CACHE 20;
CREATE SEQUENCE SOLDESK.COMMENT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 43 CACHE 20;
CREATE SEQUENCE SOLDESK.SEQ_MEMBER_NUM INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 161 CACHE 20;



/* Create Tables */

CREATE TABLE SOLDESK.BOARD_COMMENT
(
	COMMENT_NUM number NOT NULL,
	COMMENT_BOARD number NOT NULL,
	COMMENT_ID varchar2(15),
	COMMENT_DATE date,
	COMMENT_PARENT number,
	COMMENT_CONTENT varchar2(1000) NOT NULL,
	CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_NUM)
);


CREATE TABLE SOLDESK.MEMBER
(
	MB_ID varchar2(30) NOT NULL,
	MB_PW varchar2(100) NOT NULL,
	MB_NAME varchar2(10) NOT NULL,
	MB_BIRTH date NOT NULL,
	MB_GENDER varchar2(10) NOT NULL,
	MB_PH varchar2(15) NOT NULL,
	MB_EMAIL varchar2(100) NOT NULL,
	MB_REGDATE date NOT NULL,
	MB_MANAGER varchar2(20) NOT NULL,
	MB_STAT varchar2(20) NOT NULL,
	CONSTRAINT SYS_C007098 PRIMARY KEY (MB_ID)
);


CREATE TABLE SOLDESK.MEMBER_BOARD
(
	BOARD_NUM number NOT NULL,
	BOARD_ID varchar2(50),
	BOARD_SUBJECT varchar2(100),
	BOARD_CONTENT varchar2(2000),
	BOARD_FILE varchar2(100),
	BOARD_RE_REF number,
	BOARD_RE_LEV number,
	BOARD_RE_SEQ number,
	BOARD_COUNT number,
	BOARD_DATE date,
	BOARD_PARENT number(10,0),
	CONSTRAINT PK_MEMBER_BOARD PRIMARY KEY (BOARD_NUM)
);


CREATE TABLE SOLDESK.MOVIERANK
(
	MS_TITLE varchar2(100) NOT NULL,
	MS_POSTER varchar2(500),
	MS_SEQ varchar2(15),
	MS_ID varchar2(15),
	MS_CNT number,
	CONSTRAINT SYS_C007112 PRIMARY KEY (MS_TITLE)
);


CREATE TABLE SOLDESK.MOVIEREVIEW
(
	MS_NO number NOT NULL,
	MS_TITLE varchar2(50),
	MB_ID varchar2(15),
	MS_MYRATING number,
	MS_REVIEW varchar2(1000),
	MS_SEQ varchar2(15),
	MS_ID varchar2(15),
	MS_REGDATE date,
	CONSTRAINT SYS_C007113 PRIMARY KEY (MS_NO)
);


CREATE TABLE SOLDESK.MOVIESCRAP
(
	MS_NO number NOT NULL,
	MB_ID varchar2(15),
	MS_TITLE varchar2(100),
	MS_DIRECTOR varchar2(30),
	MS_POSTER varchar2(500),
	MS_REGDATE date,
	MS_RATING varchar2(50),
	MS_SEQ varchar2(15),
	MS_ID varchar2(15),
	CONSTRAINT SYS_C007086 PRIMARY KEY (MS_NO)
);



/* Create Foreign Keys */

ALTER TABLE SOLDESK.BOARD_COMMENT
	ADD CONSTRAINT FK_COMMENT FOREIGN KEY (COMMENT_BOARD)
	REFERENCES SOLDESK.MEMBER_BOARD (BOARD_NUM)
;



